## Getting the dataset from csv file

Imports

In [1]:
import io
import numpy as np
import pandas as pd
import math

Create dataframe from CSV file

In [2]:
df = pd.read_csv('FODS-A2.csv')
df = df.sample(frac = 1)
df.to_csv('FoDS-Assignment-2_Shuffled.csv')
df

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2,Appliances
1221,19.500000,34.030000,17.463333,35.290000,19.700000,36.030000,18.500000,33.290000,17.633333,59.500000,...,41.090000,0.2000,761.100000,82.000000,4.000000,40.000000,-2.60,26.630701,26.630701,60
3839,21.200000,38.790000,18.500000,42.900000,22.000000,36.900000,19.600000,37.590000,19.500000,42.900000,...,40.400000,6.6300,761.533333,90.500000,3.000000,21.333333,5.10,40.636737,40.636737,70
3646,22.600000,36.566667,24.860000,33.063333,23.790000,35.590000,23.000000,35.790000,19.600000,50.500000,...,41.000000,14.2000,754.900000,71.000000,1.000000,40.000000,8.90,6.240541,6.240541,90
6753,20.500000,42.260000,20.100000,40.400000,21.000000,41.200000,19.100000,41.200000,18.890000,49.000000,...,43.433333,5.7000,743.800000,91.000000,5.000000,40.000000,4.30,16.782268,16.782268,80
2647,21.290000,36.030000,19.200000,37.450000,22.390000,34.060000,20.926667,34.623333,18.500000,43.590000,...,35.290000,7.0500,762.200000,68.500000,3.000000,34.500000,1.60,8.847160,8.847160,120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5730,19.890000,35.260000,16.633333,40.230000,20.066667,36.466667,19.323333,35.463333,17.890000,49.000000,...,40.700000,-0.0667,769.800000,91.333333,4.000000,54.333333,-1.30,32.355743,32.355743,70
4278,24.426667,32.626667,21.890000,34.168571,23.945000,34.045000,24.100000,31.633333,23.890000,38.200000,...,30.290000,7.5200,759.933333,67.500000,4.333333,40.000000,1.85,23.695404,23.695404,70
5473,22.700000,41.090000,19.760000,45.530000,24.290000,38.790000,21.200000,41.290000,20.963333,54.060000,...,42.822500,7.6000,754.133333,86.666667,3.000000,40.000000,5.50,28.895156,28.895156,60
5348,24.000000,45.490000,22.390000,46.290000,25.790000,39.433333,24.290000,42.700000,22.390000,53.966667,...,46.500000,13.7000,755.800000,88.000000,1.333333,50.333333,11.70,43.867512,43.867512,60
5307,24.892286,46.409143,25.100000,42.489524,26.430190,41.412381,24.187941,45.058824,23.130882,51.062574,...,46.419714,23.1000,754.000000,49.000000,7.000000,40.000000,11.90,49.857168,49.857168,120

## Pre-processing

Handling missing data

In [3]:
null_counts = df.isnull().sum()
null_counts.drop([index for index in null_counts.index if null_counts[index] == 0], inplace=True)
print("The features having missing data and number of empty rows:\n")
print(null_counts)
print("---")

index_list = []
for feature in null_counts.index:
  index_list.append(df[df[feature].isnull()].index)

print(index_list)

# print the specific rows of df with NaN values for each feature
for index in index_list:
  print(df.loc[index].to_string())

df.fillna(df.mean(skipna=True, numeric_only=True), inplace=True)

# print the specific rows of df after replacing NaN values for each feature
for index in index_list:
  print(df.loc[index].to_string())

The features having missing data and number of empty rows:

Series([], dtype: int64)
---
[]

Normalisation

In [3]:
df=(df-df.mean())/df.std()
df

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2,Appliances
1221,-1.351982,-1.549858,-1.297985,-1.237769,-1.273800,-0.966676,-1.155234,-1.298137,-1.052569,0.945917,...,-0.107035,-1.352033,0.751551,0.163111,-0.017400,0.141958,-1.500322,0.114483,0.114483,-0.366001
3839,-0.302699,-0.358060,-0.831018,0.613710,-0.138397,-0.701210,-0.619814,-0.316327,-0.055749,-0.876781,...,-0.272456,-0.149372,0.810586,0.730253,-0.424468,-1.438657,0.322578,1.090106,1.090106,-0.270157
3646,0.561417,-0.914733,2.033846,-1.779507,0.745243,-1.100935,1.035118,-0.727317,-0.002348,-0.042293,...,-0.128612,1.266513,-0.093107,-0.570836,-1.238602,0.141958,1.222191,-1.305841,-1.305841,-0.078470
6753,-0.734757,0.510751,-0.110298,0.005471,-0.632050,0.610862,-0.863187,0.507937,-0.381496,-0.206994,...,0.454758,-0.323319,-1.605317,0.763614,0.389667,0.141958,0.133186,-0.571533,-0.571533,-0.174313
2647,-0.247149,-1.049103,-0.515703,-0.712250,0.054128,-1.567788,0.025934,-0.993700,-0.589760,-0.801018,...,-1.497533,-0.070816,0.901410,-0.737642,-0.424468,-0.323759,-0.506013,-1.124271,-1.124271,0.209062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5730,-1.111264,-1.241894,-1.671859,-0.035889,-1.092794,-0.833435,-0.754480,-0.801904,-0.915506,-0.206994,...,-0.200534,-1.401916,1.936797,0.785855,-0.017400,1.355644,-1.192560,0.513274,0.513274,-0.270157
4278,1.688881,-1.901222,0.696008,-1.510607,0.821759,-1.572365,1.570538,-1.676400,2.288556,-1.392846,...,-2.696239,0.017092,0.592610,-0.804365,0.118289,0.141958,-0.446828,-0.089982,-0.089982,-0.270157
5473,0.623139,0.217809,-0.263451,1.253577,0.992070,-0.124509,0.158978,0.528487,0.725686,0.348599,...,0.308316,0.032055,-0.197554,0.474483,-0.424468,0.141958,0.417274,0.272219,0.272219,-0.366001
5348,1.425532,1.319471,0.921234,1.438482,1.732550,0.071793,1.663019,0.850429,1.487541,0.338351,...,1.189964,1.172993,0.029505,0.563446,-1.102913,1.016941,1.885064,1.315153,1.315153,-0.366001
5307,1.976273,1.549604,2.141954,0.513843,2.048582,0.675666,1.613343,1.389015,1.883180,0.019478,...,1.170716,2.931160,-0.215718,-2.038731,1.203801,0.141958,1.932412,1.732376,1.732376,0.209062

Test-train splitting: 80-20

In [4]:
train_data = df.iloc[:6316]
test_data = df.iloc[6316:]

train_data = train_data.to_numpy()
test_data = test_data.to_numpy()

## Model

Input for the model

In [5]:
def input_function():
  number_of_features = int(input("Enter number of features in dataset: "))
  n = int(input("Enter number of iterations in Gradient Descent: "))
  eta = float(input("Enter the learning rate(eta): "))
  return (n, eta, number_of_features)

Linear Regression with Gradient Descent

In [6]:
def gradientDescent(index_array, no_of_iterations, eta):
  data_train = np.concatenate((np.ones(train_data.shape[0], dtype=np.float64).reshape(-1,1), train_data[:, index_array], (-1)*(train_data[:, [-1]])), axis = 1)
  data_test = np.concatenate((np.ones(test_data.shape[0], dtype=np.float64).reshape(-1,1), test_data[:, index_array], (-1)*(test_data[:, [-1]])), axis = 1)
  n_coeffs = 1 + len(index_array)
  coefficients = np.ones(n_coeffs+1).reshape(-1,1) 
  coefficients[n_coeffs] = 1 

  for _ in range(no_of_iterations):      
    
    intermediate_matrix = data_train.dot(coefficients)
    slope = np.zeros(n_coeffs)
    j = 0
    while(j < n_coeffs):
        slope[j] = float((intermediate_matrix*data_train[:, [j]]).sum())
        j = j+1
    slope = slope.reshape(-1,1) 
    coefficients[:-1, :] = coefficients[:-1, :] - (eta)*slope 

  train_error_intermediate = data_train.dot(coefficients)
  train_error_intermediate = train_error_intermediate * train_error_intermediate
  training_error = train_error_intermediate.sum()
  test_error_intermediate = data_test.dot(coefficients)
  test_error_intermediate = test_error_intermediate * test_error_intermediate
  testing_error = test_error_intermediate.sum()
  return (training_error, testing_error)

## Greedy algorithms for feature selection

Forward feature selection

In [7]:
def forwardFeatureSelection():
  number_of_iterations, eta, number_of_features = input_function()
  final_pair = [[], math.inf, math.inf]
  previous_pair = [[], math.inf]
  for i in range(number_of_features):
    current_pair = [[], math.inf]
    train_error = 0
    for j in [k for k in range(number_of_features) if k not in previous_pair[0]]:
      current_indices = [*(previous_pair[0]), j]
      temp_train_error, error = gradientDescent(current_indices, number_of_iterations, eta)
      print(current_indices, error, temp_train_error)
      if error < current_pair[1]:
        current_pair = [current_indices, error]
        train_error = temp_train_error
      
    if current_pair[1] < final_pair[1]:
      final_pair = [*current_pair, train_error]
    previous_pair = current_pair
  return final_pair

Subset of features that provide optimal model for forward feature selection and the error when trained with only that subset of features

In [ ]:
forward_result = forwardFeatureSelection()
print("The features which give optimal model with forward feature selection, testing error and training error for those features:\n")
print(df.columns[forward_result[0]], forward_result[1:])

Backward feature selection

In [8]:
def backwardFeatureSelection():
  number_of_iterations, eta, number_of_features = input_function()
  final_pair = [[], math.inf, math.inf]
  previous_pair = [list(range(number_of_features)), math.inf]
  train_error, previous_pair[1] = gradientDescent(previous_pair[0], number_of_iterations, eta)
  final_pair = [*previous_pair, train_error]

  print(previous_pair)
  for i in range(number_of_features):
    current_pair = [[], math.inf]
    train_error = 0
    for j in previous_pair[0]:
      current_indices = previous_pair[0].copy()
      current_indices.remove(j)
      temp_train_error, error = gradientDescent(current_indices, number_of_iterations, eta)
      print(current_indices, error, temp_train_error)
      if error < current_pair[1]:
        current_pair = [current_indices, error]
        train_error = temp_train_error
    if current_pair[1] < final_pair[1]:
      final_pair = [*current_pair, train_error]
    previous_pair = current_pair
  return final_pair

Subset of features that provide optimal model for backward feature selection and the errors when trained with only that subset of features

In [ ]:
backward_result = backwardFeatureSelection()
print("The features which give optimal model with backward feature selection, testing error and training error for those features:\n")
print(df.columns[backward_result[0]], backward_result[1:])

Enter number of features in dataset: 26
Enter number of iterations in Gradient Descent: 30000
Enter the learning rate(eta): 0.00001
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], 1203.5539762352291]